# ─────────────────────────────────────────────────────────
# 站点信息 / Site
# ─────────────────────────────────────────────────────────
title: 心哲空间
SEOTitle: 心哲空间 | Dasein Blog
header-img: /img/home-bg.jpg

email: 1780amadeus@gmail.com
description: "这里是心哲空间，我们将发布与心理学、哲学及人与世界相关的研究与评论。"
keyword: "心理学, 哲学, 社会科学, 结构生成论, 原初意义论, 天平论, 元行为心理学, 海德格尔, 尼采, 维特根斯坦, 禅宗, 后朋克, 意义, 自由"

# 你的 GitHub Pages 项目页地址：
# url 为用户主页域名；baseurl 为仓库路径前缀（必须以斜杠开头）
url: "https://dasein-phy.github.io"
baseurl: "/Dasein.github.io"

# 未来日期的文章是否发布
future: true
# ─────────────────────────────────────────────────────────
# 社交帐号
# ─────────────────────────────────────────────────────────
RSS: false
weibo_username:
zhihu_username: 冬酱
github_username: dasein-phy
twitter_username: FAamadeus
facebook_username:
linkedin_username:

# 其他平台
bilibili_id: UID:62861274              # 如：12345678
wechat_official_account: 心哲空间
wechat_qr: /img/wechat_qr.jpg

# 自定义外链（可选）
custom_links:
  # - { title: "Substack", url: "https://xxx.substack.com", icon: "fa-newspaper-o" }
  # - { title: "豆瓣", url: "https://www.douban.com/people/xxxx", icon: "fa-leaf" }

# ─────────────────────────────────────────────────────────
# 构建设置 / Build
# ─────────────────────────────────────────────────────────
highlighter: rouge
permalink: pretty
paginate: 10

exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md

anchorjs: true
# 如需固定到中国时区可开启：
# timezone: Asia/Shanghai

plugins:
  - jekyll-paginate

# ─────────────────────────────────────────────────────────
# Markdown
# ─────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# ─────────────────────────────────────────────────────────
# 评论与互动（默认关闭）
# ─────────────────────────────────────────────────────────
disqus_username: Dasein
netease_comment: false

# ─────────────────────────────────────────────────────────
# 分析统计（默认关闭；如需启用请填写真实 ID）
# ─────────────────────────────────────────────────────────
# ba_track_id:
# ga_track_id: ""
# ga_domain:

# ─────────────────────────────────────────────────────────
# 侧边栏
# ─────────────────────────────────────────────────────────
sidebar: true
sidebar-about-description: "严肃写作与系统建构：结构生成论—原初意义论—天平论—元行为心理学"
# 用于 Open Graph/Twitter 的预览图，建议放一张站内图像
sidebar-avatar: /img/avatar.jpg

# ─────────────────────────────────────────────────────────
# 标签区
# ─────────────────────────────────────────────────────────
featured-tags: true
featured-condition-size: 1

# ─────────────────────────────────────────────────────────
# PWA / 主题色（与你的品牌色一致）
# ─────────────────────────────────────────────────────────
chrome-tab-theme-color: "#718771"
service-worker: true

# 如果需要数学公式支持再开启
page-mathjax: false

# ─────────────────────────────────────────────────────────
# 友链（可为空）
# ─────────────────────────────────────────────────────────
friends: []
